const responseMessageCode = {
    ACTION_COMPLETE: 'ACTION_COMPLETE',
    REGISTRATION_SUCCESSFUL: 'REGISTRATION_SUCCESSFUL',
    LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
    LOGIN_SUCCESSFULLY_NOT_VERIFY: 'LOGIN_SUCCESSFULLY_NOT_VERIFY',
    INCORRECT_WALLET_ADDRESS: 'INCORRECT_WALLET_ADDRESS',
    INCORRECT_EMAIL_PASSWORD: 'INCORRECT_EMAIL_PASSWORD',
    MAX_LOGIN_DEVICES_REACHED: 'MAX_LOGIN_DEVICES_REACHED',
    PARAMETER_MISSING: 'PARAMETER_MISSING',
    MISSING_PARAMETER: 'MISSING_PARAMETER',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    INVALID_SOCIAL_LOGIN: 'INVALID_SOCIAL_LOGIN',
    CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
    OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    ERROR_IN_EXECUTION: 'ERROR_IN_EXECUTION',
    UPLOAD_ERROR: 'UPLOAD_ERROR',
    PASSWORD_CHANGED_SUCCESSFULLY: 'PASSWORD_CHANGED_SUCCESSFULLY',
    WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
    NOT_A_VALID_IMAGE_LIST: 'NOT_A_VALID_IMAGE_LIST',
    SIZE_EXCEEDS: 'SIZE_EXCEEDS',
    VIDEO_SIZE_EXCEEDS: 'VIDEO_SIZE_EXCEEDS',
    ACCOUNT_NOT_REGISTER: 'ACCOUNT_NOT_REGISTER',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    NO_DATA_FOUND: 'NO_DATA_FOUND',
    NO_USER_FOR_THIS_TOKEN: 'NO_USER_FOR_THIS_TOKEN',
    PLEASE_PROVIDE_TOKEN: 'PLEASE_PROVIDE_TOKEN',
    INVALID_OTP: 'INVALID_OTP',
    ERROR_IN_SENDING_OTP: 'ERROR_IN_SENDING_OTP',
    DISABLED_ACCOUNT: 'DISABLED_ACCOUNT',
    USER_SUBSCRIBED_SUCCESSFULLY: 'USER_SUBSCRIBED_SUCCESSFULLY',
    INVALID_CODE: 'INVALID_CODE',
    ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
    VERSION_FETCHED: 'VERSION_FETCHED',
    USER_NOT_EXIST: 'USER_NOT_EXIST',
    PLAN_EXISTS: 'PLAN_EXISTS',
    ADD_PAYMENT_CARD: 'ADD_PAYMENT_CARD',
    COACH_BANK_DETAILS: 'COACH_BANK_DETAILS',
    FORGOT_PASSWORD_MAIL_EXPIRE: 'FORGOT_PASSWORD_MAIL_EXPIRE',
    SAME_PREFRENCES: 'SAME_PREFRENCES',
    SELECT_PREFRENCES: 'SELECT_PREFRENCES',
    FIND_ME: 'FIND_ME',
    FEEDBACK: 'FEEDBACK',
    FEEDBACK_ERROR: 'FEEDBACK_ERROR',
    DEVICE_TOKEN_UPDATED: 'DEVICE_TOKEN_UPDATED',
    USER_AVAILABLE: 'USER_AVAILABLE',
    DOB_MAX_UPDATE: 'DOB_MAX_UPDATE',
    MULTIPLE_PICS_COUNT: 'MULTIPLE_PICS_COUNT',
    TICKET_VIEWED: 'TICKET_VIEWED',
    PLAN_ID_NOT_VALID: 'PLAN_ID_NOT_VALID',
    ACTIVE_SUBSCRIPTION: 'ACTIVE_SUBSCRIPTION',
    INVALID_CARD: 'INVALID_CARD',
    ACTIVE_CARD: 'ACTIVE_CARD',
    COACH_SUBSCRIPTION_PLAN_NOT_AVAILED: 'COACH_SUBSCRIPTION_PLAN_NOT_AVAILED',
    COACH_MAX_BANK_ACCOUNT: 'COACH_MAX_BANK_ACCOUNT',
    COACH_ACCOUNT_ERROR: 'COACH_ACCOUNT_ERROR',
    PAYOUT_ACCOUNT: 'PAYOUT_ACCOUNT',
    REQUEST_ALREADY_SENT: 'REQUEST_ALREADY_SENT',
    ALREADY_FRIEND: 'ALREADY_FRIEND',
    ALREADY_INTERESTED: 'ALREADY_INTERESTED',
    ALREADY_VIEWED_DEAL: 'ALREADY_VIEWED_DEAL',
    EMPTY_PREFRENCES: 'EMPTY_PREFRENCES',
    ALREADY_FOLLOWED: 'ALREADY_FOLLOWED',
    ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED',
    OTP_IS_SEND_ON_REGISTERED_EMAIL: 'OTP_IS_SEND_ON_REGISTERED_EMAIL',
    FRIEND_REQUEST_CANCLLED: 'FRIEND_REQUEST_CANCLLED',
    EVENT_REQUEST_ACCEPETD: 'EVENT_REQUEST_ACCEPETD',
    REQUEST_SENT: 'REQUEST_SENT',
    GROUP_CHAT_DELETED: 'GROUP_CHAT_DELETED',
    FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
    FRIEND_REQUEST_REJECTED: 'FRIEND_REQUEST_REJECTED',
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    CHECK_EMAIL_FOR_VERIFICATION_CODE: 'CHECK_EMAIL_FOR_VERIFICATION_CODE',
    DEACTIVE_ACCOUNT: 'DEACTIVE_ACCOUNT',
    CREATE_GROUP_ACTIVITY: 'CREATE_GROUP_ACTIVITY',
    GROUP_ACTIVITY_UPDATED: 'GROUP_ACTIVITY_UPDATED',
    DEAL_ADDED: 'DEAL_ADDED',
    GROUP_EDIT: 'GROUP_EDIT',
    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_EVENT: 'CREATE_EVENT',
    EVENT_UPDATED: 'EVENT_UPDATED',
    FEED_POSTED: 'FEED_POSTED',
    LINKUP_ACTIVITY_CREATED: 'LINKUP_ACTIVITY_CREATED',
    LINKUP_UPDATED: 'LINKUP_UPDATED',
    INVALID_SUBSCRIPTION: 'INVALID_SUBSCRIPTION',
    MAXIMUM_CAPACITY_CREATOR: 'MAXIMUM_CAPACITY_CREATOR',
    MAXIMUM_CAPACITY_MEMBER: 'MAXIMUM_CAPACITY_MEMBER',
    GROUP_CAHT_MEMBER_ERROR: 'GROUP_CAHT_MEMBER_ERROR',
    DISABLE_LINKUP_ACTIVITY: 'DISABLE_LINKUP_ACTIVITY',
    ACTIVITY_ALREADY_REPORTED: 'ACTIVITY_ALREADY_REPORTED',
    GROUP_ALREADY_REPORTED: 'GROUP_ALREADY_REPORTED',
    OWN_ACTIVITY_REPORT: 'OWN_ACTIVITY_REPORT',
    OWN_GROUP_REPORT: 'OWN_GROUP_REPORT',
    OWN_PROFILE_REPORT: 'OWN_PROFILE_REPORT',
    USER_ALREADY_REPORT: 'USER_ALREADY_REPORT',
};

const responseMessageFlags = {
    ACTION_COMPLETE: 200,
    CLIENT_ERROR: 400,
    INTERNAL_SERVER_ERROR: 500,
    UNAUTHORIZED: 401,
    BAD_REQUEST: 400
};

const colorCodes = {
    FgBlack: '\x1b[30m\x1b[1m%s\x1b[0m',
    FgRed: '\x1b[31m\x1b[1m%s\x1b[0m',
    FgGreen: '\x1b[32m\x1b[1m%s\x1b[0m',
    FgYellow: '\x1b[33m\x1b[1m%s\x1b[0m',
    FgBlue: '\x1b[34m\x1b[1m%s\x1b[0m',
    FgMagenta: '\x1b[35m\x1b[1m%s\x1b[0m',
    FgCyan: '\x1b[36m\x1b[1m%s\x1b[0m',
    FgWhite: '\x1b[37m\x1b[1m%s\x1b[0m'
};

const ALLOWED_IMAGE_MIME_TYPE = [
    'image/jpeg',
    'image/jpg',
    'image/pjpeg',
    'image/png',
    'image/*'
];

const ALLOWED_VIDEO_MIME_TYPE = ['video/mp4', 'video/*'];
const MAX_IMAGE_SIZE_ALLOWED = '5242880'; // 5 MB
const MAX_VIDEO_SIZE_ALLOWED = '10485760'; // 10 MB

const IMAGE_DIMESIONS = {
    small_thumb: {
        width: 250,
        height: 250,
        key_name: 'small_thumb'
    },
    medium_thumb: {
        width: 400,
        height: 400,
        key_name: 'medium_thumb'
    }
};

const redisConnection = {
    DEVELOPMENT_USER: 'dev_',
    PRODUCTION_USER: 'prod_'
};

module.exports = {
    responseMessageCode,
    responseMessageFlags,
    colorCodes,
    ALLOWED_IMAGE_MIME_TYPE,
    ALLOWED_VIDEO_MIME_TYPE,
    MAX_IMAGE_SIZE_ALLOWED,
    MAX_VIDEO_SIZE_ALLOWED,
    IMAGE_DIMESIONS,
    redisConnection
};
